### ISSUE TITLE
Running the tomcat profile adds entries to NOTICE

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eurekaclinical-admin-webapp#13]
Running the tomcat profile adds entries for the dependencies in the tomcat profile to the NOTICE file. This should not happen. Our practice is to require calling mvn notice:generate to add dependencies to the NOTICE, and in any case, the dependencies in the tomcat profile should not be in NOTICE.

**Comment by ndeshpa** [comment]
Fixed the issue.
